### ISSUE TITLE
Hi, I would like to ask a question! Not a really issue.

### ISSUE THREAD

**Issue by Slen1337** [OmarBaltaji/NextCut#1]
Have a good day, sir! I would like to ask you. Do you still own the chatApp firebase functional code source builded using this source:
https://github.com/duytq94/reactjs-chat-demo/issues/1 
If you still have one, may I ask you to share it? If that's not a problem for you. I'm doing an app with orders\docs and chit-chat inside every-order. My first attempt to build chat so :)

**Comment by OmarBaltaji** [comment]
@Slen1337  Hi there, hope you are having a good day as well. I wouldn't say I own this code as I really just copied duytq94's code and then turned it into functional with a help of a friend of mine. But yeah we are more than happy to share it!
This is the location of the chat code: 
https://github.com/OmarBaltaji/NextCut/tree/master/NextCut/resources/js/components/New%20Chat

Best of luck!

**Comment by Slen1337** [comment]
@OmarBaltaji  Sup again! Didn't expect such a lightning fast answer. I'm ok with functional programming but have a little leaks and misunderstanding in classes so it will be challenging for me to convert it and understand how chat works from inside (I will try to do this on my own a little later and compare it to the intel(your plus yours friend code), so this is win - win situation!). I am very glad that you shared it. Big thanks!

Have a good day! Cheers!
